<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eUShop.BusinessLogic\eUShop.BusinessLogic.csproj" />
    <ProjectReference Include="..\eUShop.Domains\eUShop.Domains.csproj" />
  </ItemGroup>

</Project>
